require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  Exclude:
    - bin/*
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Exclude:
    - fulfil_api.gemspec

Metrics/ClassLength:
  Exclude:
    - test/**/*_test.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*_test.rb

Minitest/MultipleAssertions:
  Max: 5

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
