require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  Exclude:
    - bin/*
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
